spring:
  datasource:
    dynamic:
      primary: w1
      #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        w1:
          url: jdbc:postgresql://localhost:55432/study
          username: user
          password: pw
          driver-class-name: org.postgresql.Driver
        r1:
          url: jdbc:postgresql://localhost:55433/study
          username: user
          password: pw
          driver-class-name: org.postgresql.Driver
