version: '3.8'
services:
  db_w1:
    image: postgres
    restart: unless-stopped
    ports:
      - "55432:5432"
    volumes:
      - ./data/db_w1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pw
      - POSTGRES_USER=user
      - POSTGRES_DB=study
  db_r1:
    image: postgres
    restart: unless-stopped
    ports:
      - "55433:5432"
    volumes:
      - ./data/db_r1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pw
      - POSTGRES_USER=user
      - POSTGRES_DB=study